### ISSUE TITLE
Select doesn't work as expected inside Dialog element

### ISSUE THREAD

**Issue by FasalMohammadh** [radix-ui/primitives#2450]
## Bug report
Select doesn't work as expected inside Dialog element

### Current Behavior
![image](https://github.com/radix-ui/primitives/assets/105656186/6f45410f-adcd-4dcc-bf3b-6155fb8f8d94)

- When I try to close the select via `escape` doesn't work it closes the modal and the select overlay persists so you cannot click UI element only keyboard navigate
- Arrow keys &duarr;  on select for navigation won't work inside dialog
- Select item selection and hover selection also won't work
- Dialog open and closes and then opens this happens instantly (it doesn't fully close and reopen). I checked this multiple times if I remove select from dialog it works perfectly

### Expected behavior

- expected `escape` will close the select and the second `escape` will close the modal
- expected other events also work like navigation with arrow keys
- expected at least both overlays of dialog and select disappear on `escape` 

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    select     |  1.2.2       |
| Radix Package(s) |    dialog|  1.0.5       |
| React            | n/a     |      18.2.0   |
| Browser          |      Edge(Chromium)  | 117.0.2045.60  |
| Assistive tech   |         |         |
| Node             | n/a     |  18.17.1       |
| npm/yarn         |  PNPM       |  8.8.0       |
| Operating System |    Windows     | 10  22H2      |

**Comment by joaom00** [comment]
https://github.com/radix-ui/primitives/issues/2448#issuecomment-1758293731

**Comment by botv** [comment]
Upgrading to @radix-ui/react-select 2.0.0 fixed the issue for me.

**Comment by benoitgrelard** [comment]
Yes, this was fixed a while ago and works fine with the latest versions.

**Comment by BrianChesbrough** [comment]
> Yes, this was fixed a while ago and works fine with the latest versions.

@benoitgrelard We have dialog version 1.05 and select version 2.0 and are still able to reproduce this. 
Verified it repos on chrome, mozilla and safari.

packages.json:
<img width="410" alt="image" src="https://github.com/radix-ui/primitives/assets/27379070/3c3411ac-ab46-482d-87c8-bf313c446b4a">

Video of Repo
https://youtu.be/FGvvySExH1c

**Comment by joaom00** [comment]
> > Yes, this was fixed a while ago and works fine with the latest versions.
> 
> @benoitgrelard We have dialog version 1.05 and select version 2.0 and are still able to reproduce this. Verified it repos on chrome, mozilla and safari.
> 
> packages.json: <img alt="image" width="410" src="https://private-user-images.githubusercontent.com/27379070/331740012-3c3411ac-ab46-482d-87c8-bf313c446b4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNzIxMjMsIm5iZiI6MTcxNjA3MTgyMywicGF0aCI6Ii8yNzM3OTA3MC8zMzE3NDAwMTItM2MzNDExYWMtYWI0Ni00ODJkLTg3YzgtYmYzMTNjNDQ2YjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDIyMzcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MTk3NjA5NGUxODVjYjIzYjMzYmQxZGFjODMwNGNjOTk1N2UxNDYwZTJiNTRkODdhOWVjOTViMTVmOWYzZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nwbiLifk9wweukFDymYWuh1UYKJ-PxxFhsejK9a1OWI">
> 
> Video of Repo https://youtu.be/FGvvySExH1c

Did you delete lock file and reinstall the packages? I've had to do this a few times :sweat_smile:

**Comment by BrianChesbrough** [comment]
> Did you delete lock file and reinstall the packages? I've had to do this a few times 😅
After doing that I do see the follow change to the react-select area of the lock file, however the issue still repos :(


<img width="1758" alt="Screenshot 2024-05-20 at 10 27 25 AM" src="https://github.com/radix-ui/primitives/assets/27379070/dbc71f8d-ee30-4305-b540-33810084351c">

**Comment by BrianChesbrough** [comment]
> > Did you delete lock file and reinstall the packages? I've had to do this a few times 😅
> > After doing that I do see the follow change to the react-select area of the lock file, however the issue still repos :(
> 
> <img alt="Screenshot 2024-05-20 at 10 27 25 AM" width="1758" src="https://private-user-images.githubusercontent.com/27379070/332149671-dbc71f8d-ee30-4305-b540-33810084351c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjY1NDEsIm5iZiI6MTcxNjIyNjI0MSwicGF0aCI6Ii8yNzM3OTA3MC8zMzIxNDk2NzEtZGJjNzFmOGQtZWUzMC00MzA1LWI1NDAtMzM4MTAwODQzNTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE3MzA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNTRiM2E1Y2UyNjc5OWQzODI5NWMxNzM0ZTdmM2Y1NTdmNjc1ZjRiZmM2ZDk2NGJiZDE3YzU4ZjRlYzE5Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tdewbepc3dA37tsNYp7icwd6eZ-EqoMpzap-P9wWOfw">

Do your dependencies look the same? Perhaps its something deeper that is causing this issue to continue for us.

**Comment by BrianChesbrough** [comment]
Would love to get help closing out this issue

**Comment by har1kaush1k** [comment]
Still having problems with a similar issue. When a Select is open inside a Dialog (for which the open state is managed explicitly) and I click outside the Dialog both the Select and Dialog close, but the app is then unresponsive to mouse input.

**Comment by leognmotta** [comment]
using latest vesion with the same problem, impossible to use it with modals

**Comment by leognmotta** [comment]
matched version, did everything I could find, but doing this is the only way I managed to get expected behavior 

```javascript
import { useState } from 'react'
import { DialogContent } from '@radix-ui/react-dialog'
import { Select, SelectTrigger, SelectContent } from '@radix-ui/react-select'

const MyComponent = () => {
  const [openSelect, setOpenSelect] = useState(false)

  return (
    <DialogContent
      onEscapeKeyDown={(e) => openSelect && e.preventDefault()}
      onPointerDownOutside={(e) => openSelect && e.preventDefault()}
    >
      <Select open={openSelect} onOpenChange={setOpenSelect}>
        <SelectTrigger>Open Select</SelectTrigger>
        <SelectContent onEscapeKeyDown={() => setOpenSelect(false)}>
          {/* Select items go here */}
        </SelectContent>
      </Select>
    </DialogContent>
  )
}

export default MyComponent
```

**Comment by williamlmao** [comment]
Broken again with 

"@radix-ui/react-select": "2.1.4",

"@radix-ui/react-dialog": "1.1.4",

**Comment by treyhuffine** [comment]
It looks like this is still broken in the latest

@radix-ui/react-dialog@1.1.6
@radix-ui/react-select@2.1.6

**Comment by zammit123** [comment]
I have updated to the latest version and this is still a problem.

"@radix-ui/react-select": "2.1.6",

"@radix-ui/react-dialog": "1.1.6",

**Comment by KinanGH98** [comment]
I found a fix for this issue here: https://github.com/shadcn-ui/ui/issues/1748#issuecomment-2720130543

**Comment by zammit123** [comment]
> I found a fix for this issue here: [shadcn-ui/ui#1748 (comment)](https://github.com/shadcn-ui/ui/issues/1748#issuecomment-2720130543)

Thanks for your suggestion. It did not work for me however it looks like it worked for others!
I've reverted to using a radio group as it was a short list of options.

**Comment by ianpaschal** [comment]
I'm also experiencing this using:

- `"@radix-ui/react-dialog": "^1.1.1"`
- `"@radix-ui/react-select": "^2.1.1",`

My setup isn't terribly exotic:

```tsx
<Dialog.Root open={open}>
  <AnimatePresence onExitComplete={handleCloseComplete}>
    {open && (
      <Dialog.Portal forceMount>
        <Dialog.Overlay forceMount className={styles.Overlay} onClick={handleInteractOutside} />
        <div className={styles.Positioner} tabIndex={-1}>
          <Dialog.Content
            className={clsx(styles.Content, className, { [styles[`Content-${width}`]]: true })}
            aria-describedby={undefined}
            onInteractOutside={handleInteractOutside}
            tabIndex={-1}
            asChild
            forceMount
          >
            <motion.div {...animationProps}>
              <Select.Root onValueChange={onChange} disabled={disabled} value={value} {...props}>
                <Select.Trigger className={clsx('InputSelectTrigger', { 'InputSelectTrigger--hasError': hasError, 'InputSelectTrigger--disabled': disabled })}>
                  <Select.Value ref={ref} placeholder={placeholder} />
                  <Icon className="SelectIcon">
                    <ChevronDown />
                  </Icon>
                </Trigger>
                <Select.Portal>
                  <Select.Content className="SelectContent">
                    <Select.ScrollUpButton className="SelectScrollButton">
                      <ChevronUpIcon />
                    </Select.ScrollUpButton>
                    <Select.Viewport className="SelectViewport">
                      {options.map((item, i) => (
                        <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>
                      ))}
                    </Select.Viewport>
                    <Select.ScrollDownButton className="SelectScrollButton">
                      <ChevronDownIcon />
                    </Select.ScrollDownButton>
                  </Select.Content>
                </Select.Portal>
              </Select.Root>
              {canCancel && (
                <Dialog.Close className={styles.Close} onClick={handleCancel}>
                  <X />
                </Close>
              )}
            </motion.div>
          </Dialog.Content>
        </div>
      </Dialog.Portal>
    )}
  </AnimatePresence>
</Dialog.Root>
```

**Comment by MuhibAhmed** [comment]
> I found a fix for this issue here: [shadcn-ui/ui#1748 (comment)](https://github.com/shadcn-ui/ui/issues/1748#issuecomment-2720130543)

This worked for me. I had to delete node_modules and then npm install after updating the packages like Select, drop-down, dialog, Alert dialog to the same minor version for ex,
` 
    "@radix-ui/react-checkbox": "^1.1.4",
    "@radix-ui/react-dialog": "^1.1.4",
    "@radix-ui/react-dismissable-layer": "1.1.4",
    "@radix-ui/react-dropdown-menu": "^2.1.4",
    "@radix-ui/react-menubar": "^1.1.4",
    "@radix-ui/react-popover": "^1.1.4",
    "@radix-ui/react-select": "^2.1.4",
`

**Comment by amav96** [comment]
> onEscapeKeyDown={(e) => openSelect && e.preventDefault()}
>       onPointerDownOutside={(e) => openSelect && e.preventDefault()}

until today the problem is still. Your solution is a good patch for the moment

**Comment by amav96** [comment]
I get the same problem. When i use select inside a dialog is a big problem because when click outside select both is closed. No way to fix clearly haha. by now you can do

`
 <DialogContent  
      onEscapeKeyDown={(e) =>  e.preventDefault()}
      onPointerDownOutside={(e) =>  e.preventDefault()}>
`
only where you want stop propagation
