### ISSUE TITLE
Проблема с автоматическим отлючением скролла при открытом SelectMenu, где данную настройку нельзя менять

### ISSUE THREAD

**Issue by qwesmayn** [radix-ui/primitives#3276]
I've run into a problem where I can't remove the automatic scroll lock when opening a menu. The documentation didn't say anything about this thing and its setting. I tried for a couple of days at least some option to disable the scroll lock and the only option was to remove the use. In the end I had to get into the root of the radix library and disable its use. Please make it possible to disable this function through props or any other implementation. Maybe I'm wrong and there is an add-on, hint if it really exists.

**Comment by qwesmayn** [comment]
I'm talking about Select here

**Comment by danieldunderfelt** [comment]
Running into the same issue. Many components from Radix disable scrolling or set pointer-events none on body, and sometimes it gets stuck. This whole thing makes Radix pretty non-viable for me. I'm just using Shadcn components normally and the app often gets stuck in some weird non-interaction state, with the console showing errors about "Blocked aria-hidden on an element". I have no idea how or why people put up with this to make these libraries so popular.

I just need an option to disable all this scroll locking and pointer-events none stuff.

**Comment by danieldunderfelt** [comment]
Running into the same issue. Many components from Radix disable scrolling or set pointer-events none on body, and sometimes it gets stuck. This whole thing makes Radix pretty non-viable for me, and it would all be solved with a simple option to disable all this scroll locking and pointer-events none stuff.

**Comment by daniellesuper** [comment]
Also running into this issue here. does anybody have a temporary solution to enable scrolling on the body when the select content is open?

**Comment by phu130201** [comment]
> Running into the same issue. Many components from Radix disable scrolling or set pointer-events none on body, and sometimes it gets stuck. This whole thing makes Radix pretty non-viable for me, and it would all be solved with a simple option to disable all this scroll locking and pointer-events none stuff.

How can you fix it, the same issues with pointer-events none too

**Comment by Mandersen21** [comment]
same issues with this problem

**Comment by qwesmayn** [comment]
The problem is still not solved, why not add a property as in dropdown-menu

![Image](https://github.com/user-attachments/assets/dfdb4caa-961d-4aa4-97e3-9bdc3e008510)

**Comment by christiannaths** [comment]
Yeah, this is a bummer, and it's not in-line with how native select works (Chrome/Macos anyway). But I think I can see where the decision was made as native select does block scrolling but doesn't remove the scroll bar.

Anyway, in case it helps anyone else, someone posted a workaround (albeit definitely not a fix) in the shadcn issues: https://github.com/shadcn-ui/ui/issues/4227#issuecomment-2438290165

Hope this gets looked at and fixed 🙏

**Comment by AminPainter** [comment]
```
import { useLayoutEffect } from 'react';

/**
 * Hook to prevent scroll locking when drawer/dialog is open
 *
 * PROBLEM:
 * shadcn's Drawer component (built on Vaul + Radix Dialog) uses react-remove-scroll
 * to lock body scrolling when a drawer opens. This involves:
 * 1. Setting body styles: overflow: hidden, position: relative, margin-right (for scrollbar)
 * 2. Adding JavaScript event listeners to prevent wheel/touch events
 * 3. Adding data-scroll-locked="1" attribute to body element to indicate scroll is locked
 *
 * REQUIREMENT:
 * We need background scrolling to remain enabled for low-resolution screens where
 * users need to scroll the page content behind the drawer, while keeping the overlay visible.
 *
 * WHY THE HACK IS NEEDED:
 * - CSS alone (overflow: auto !important) fixes the scrollbar visibility but doesn't
 *   re-enable trackpad/wheel scrolling because react-remove-scroll's JavaScript event
 *   listeners call preventDefault() on wheel/touchmove events
 * - Vaul's disablePreventScroll prop only affects input repositioning, not body scroll lock
 * - The scroll lock comes from Radix Dialog's internal use of react-remove-scroll,
 *   which doesn't expose a way to disable just the scroll lock while keeping modal behavior
 *
 * SOLUTION:
 * This hook intercepts scroll events in the capture phase (before react-remove-scroll's
 * listeners) and stops propagation when data-scroll-locked="1" is present, effectively
 * preventing react-remove-scroll from blocking the scroll while allowing the native
 * browser scroll behavior to continue.
 *
 * Combined with, this restores full scroll functionality
 * layer base {
 *  body[data-scroll-locked='1'] {
 *     overflow: auto !important;
 *   }
 * }
 * (both scrollbar and trackpad) while maintaining the drawer's modal overlay.
 */

const usePreventScrollLock = () => {
  useLayoutEffect(() => {
    const handler = (e: Event) => {
      if (document.body.getAttribute('data-scroll-locked') === '1') {
        e.stopImmediatePropagation();
      }
    };

    const eventTypes = ['wheel', 'scroll', 'touchmove'] as const;

    const options = { capture: true, passive: false };
    eventTypes.forEach((type) => {
      window.addEventListener(type, handler, options);
    });

    return () => {
      eventTypes.forEach((type) => {
        window.removeEventListener(type, handler, options);
      });
    };
  }, []);
};

export default usePreventScrollLock;

```
